/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations['health_api_v1_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/settings/catalog': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Settings-Katalog laden
     * @description Liefert die versionierte Navigations- und Metadatenstruktur der Kernschmied-Einstellungen. Der Katalog enthält keine Secrets und ersetzt keine serverseitige Autorisierung.
     */
    get: operations['get_settings_catalog_api_v1_settings_catalog_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/bootstrap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Frontend-Bootstrap laden
     * @description Liefert die initialen, nicht sensiblen Laufzeitinformationen für das schema-gesteuerte Frontend. Der Bootstrap ersetzt keine serverseitige Autorisierung.
     */
    get: operations['bootstrap_api_v1_bootstrap_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ui/schema': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * UI-Schema laden
     * @description Liefert den versionierten, schema-gesteuerten UI-Vertrag. Das Frontend darf ausschließlich bekannte Komponenten- und Aktionstypen aus seinen festen Registries ausführen.
     */
    get: operations['ui_schema_api_v1_ui_schema_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/calendar/selection': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Select Date
     * @description Persist a selected calendar date. Integration point for frontend calendar.
     */
    post: operations['select_date_api_v1_calendar_selection_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/calendars/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Calendars */
    get: operations['list_calendars_api_v1_calendars__get'];
    put?: never;
    /** Create Calendar */
    post: operations['create_calendar_api_v1_calendars__post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/calendars/{calendar_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Calendar */
    get: operations['get_calendar_api_v1_calendars__calendar_id__get'];
    put?: never;
    post?: never;
    /** Delete Calendar */
    delete: operations['delete_calendar_api_v1_calendars__calendar_id__delete'];
    options?: never;
    head?: never;
    /** Patch Calendar */
    patch: operations['patch_calendar_api_v1_calendars__calendar_id__patch'];
    trace?: never;
  };
  '/api/v1/calendars/{calendar_id}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Events */
    get: operations['list_events_api_v1_calendars__calendar_id__events_get'];
    put?: never;
    /** Create Event */
    post: operations['create_event_api_v1_calendars__calendar_id__events_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/calendars/{calendar_id}/events/{event_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Event */
    get: operations['get_event_api_v1_calendars__calendar_id__events__event_id__get'];
    put?: never;
    post?: never;
    /** Delete Event */
    delete: operations['delete_event_api_v1_calendars__calendar_id__events__event_id__delete'];
    options?: never;
    head?: never;
    /** Patch Event */
    patch: operations['patch_event_api_v1_calendars__calendar_id__events__event_id__patch'];
    trace?: never;
  };
  '/api/v1/hierarchy': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Hierarchie laden
     * @description Liefert die generische Projekt-/Mandanten-/Objekthierarchie für das schema-gesteuerte Frontend.
     */
    get: operations['hierarchy_api_v1_hierarchy_get'];
    put?: never;
    /** Hierarchieknoten erstellen */
    post: operations['create_hierarchy_node_api_v1_hierarchy_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/hierarchy/{node_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Hierarchieknoten löschen */
    delete: operations['delete_hierarchy_node_api_v1_hierarchy__node_id__delete'];
    options?: never;
    head?: never;
    /** Hierarchieknoten aktualisieren */
    patch: operations['update_hierarchy_node_api_v1_hierarchy__node_id__patch'];
    trace?: never;
  };
  '/api/v1/hierarchy/{node_id}/move': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Hierarchieknoten verschieben */
    post: operations['move_hierarchy_node_api_v1_hierarchy__node_id__move_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/hierarchy/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mehrere Knoten atomar neu anordnen */
    post: operations['reorder_hierarchy_nodes_api_v1_hierarchy_reorder_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/documentation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Dokumentationsübersicht laden */
    get: operations['list_documentation_api_v1_documentation_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/documentation/pages/{page_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Dokumentationsseite laden */
    get: operations['get_documentation_page_api_v1_documentation_pages__page_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/models/providers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Verfügbare Modellprovider auflisten
     * @description Liefert die Provider der registrierten Modelle. Es werden keine Zugangsdaten oder internen Providerdetails ausgegeben.
     */
    get: operations['providers_api_v1_models_providers_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/models': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Verfügbare Modelle auflisten
     * @description Liefert die serverseitig registrierten und für das Frontend sichtbaren Modelle. Die Sichtbarkeit ersetzt keine Autorisierung bei einer späteren Modellauswahl.
     */
    get: operations['models_api_v1_models_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tools': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Verfügbare Tools auflisten
     * @description Liefert die registrierten und für das Frontend sichtbaren Tools. Die Listung eines Tools stellt keine Ausführungsfreigabe dar.
     */
    get: operations['tools_api_v1_tools_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/chat/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Chat-Antwort streamen
     * @description Erzeugt eine Chat-Antwort als versionierten Server-Sent-Events-Datenstrom.
     */
    post: operations['stream_chat_api_v1_chat_stream_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Konfiguration auflisten
     * @description Liefert die sichtbare Fachkonfiguration und die aktuelle Revision. Sensible Werte werden nicht ausgegeben.
     */
    get: operations['list_config_api_v1_config_get'];
    /**
     * Mehrere Konfigurationswerte ändern (Bulk)
     * @description Nimmt ein gruppiertes `values`-Objekt entgegen und speichert alle enthaltenen Werte in einer Transaktion.
     */
    put: operations['bulk_update_config_api_v1_config_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/config/{group}/{key}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Konfigurationswert ändern
     * @description Ändert einen registrierten, runtime-editierbaren Konfigurationswert. Die Änderung wird anhand des Settings-Katalogs validiert, versioniert und protokolliert.
     */
    put: operations['update_config_api_v1_config__group___key__put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Anwendungsstatus */
    get: operations['root__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * BootstrapApplication
     * @description Grundinformationen über die laufende Anwendung.
     */
    BootstrapApplication: {
      /** Name */
      name: string;
      /** Version */
      version: string;
      /**
       * Environment
       * @enum {string}
       */
      environment: 'development' | 'intranet' | 'internet';
      /** Api Prefix */
      api_prefix: string;
    };
    /**
     * BootstrapCapabilities
     * @description Technische Verfügbarkeit von Modulen.
     *
     *     Diese Werte sind keine Berechtigungsentscheidung. Jeder aufgerufene
     *     Endpunkt muss die jeweilige Benutzeraktion erneut serverseitig
     *     autorisieren.
     */
    BootstrapCapabilities: {
      /**
       * Hierarchy
       * @default false
       */
      hierarchy: boolean;
      /**
       * Ui Schema
       * @default false
       */
      ui_schema: boolean;
      /**
       * Chat Streaming
       * @default false
       */
      chat_streaming: boolean;
      /**
       * Chat Persistence
       * @default false
       */
      chat_persistence: boolean;
      /**
       * Model Registry
       * @default false
       */
      model_registry: boolean;
      /**
       * Model Service
       * @default false
       */
      model_service: boolean;
      /**
       * Tool Registry
       * @default false
       */
      tool_registry: boolean;
      /**
       * Configuration
       * @default false
       */
      configuration: boolean;
      /**
       * Configuration Admin
       * @default false
       */
      configuration_admin: boolean;
      /**
       * File Upload
       * @default false
       */
      file_upload: boolean;
      /**
       * Audit Log
       * @default false
       */
      audit_log: boolean;
    };
    /**
     * BootstrapEndpoints
     * @description Zentrale API-Einstiegspunkte für das Frontend.
     *
     *     Die Pfade werden aus dem tatsächlich konfigurierten API-Prefix
     *     erzeugt und nicht mehrfach im Frontend fest verdrahtet.
     */
    BootstrapEndpoints: {
      /** Bootstrap */
      bootstrap: string;
      /** Ui Schema */
      ui_schema: string;
      /** Hierarchy */
      hierarchy: string;
      /** Chat Stream */
      chat_stream: string;
      /** Chats */
      chats: string;
      /** Configuration */
      configuration: string;
      /** Models */
      models: string;
      /** Tools */
      tools: string;
      /** Health Live */
      health_live: string;
      /** Health Ready */
      health_ready: string;
    };
    /**
     * BootstrapFeatures
     * @description Für das Frontend sichtbare technische Betriebsmerkmale.
     */
    BootstrapFeatures: {
      /**
       * Schema Driven Ui
       * @default true
       */
      schema_driven_ui: boolean;
      /**
       * Recursive Hierarchy
       * @default true
       */
      recursive_hierarchy: boolean;
      /**
       * Server Side Authorization
       * @default true
       */
      server_side_authorization: boolean;
      /**
       * Streaming Transport
       * @default sse
       * @constant
       */
      streaming_transport: 'sse';
      /**
       * Dynamic Models
       * @default false
       */
      dynamic_models: boolean;
      /**
       * Dynamic Tools
       * @default false
       */
      dynamic_tools: boolean;
      /**
       * Runtime Configuration
       * @default false
       */
      runtime_configuration: boolean;
    };
    /**
     * BootstrapResponse
     * @description Stabiler und versionierter Bootstrap-Vertrag.
     */
    BootstrapResponse: {
      /**
       * Schema Version
       * @default 1.1
       */
      schema_version: string;
      /**
       * Api Version
       * @default v1
       */
      api_version: string;
      application: components['schemas']['BootstrapApplication'];
      /**
       * Environment
       * @enum {string}
       */
      environment: 'development' | 'intranet' | 'internet';
      user: components['schemas']['BootstrapUser'];
      /** Security Profile */
      security_profile: {
        [key: string]: unknown;
      };
      capabilities: components['schemas']['BootstrapCapabilities'];
      features: components['schemas']['BootstrapFeatures'];
      versions: components['schemas']['BootstrapVersions'];
      endpoints: components['schemas']['BootstrapEndpoints'];
      revisions: components['schemas']['BootstrapRevisions'];
      /** Config Revision */
      config_revision: number;
      /** Request Id */
      request_id?: string | null;
      /**
       * Minimum Client Version
       * @description Erforderliche Mindestversion des Frontends.
       */
      minimum_client_version?: string | null;
      /**
       * Feature Flags
       * @description Feature-Flags für das Frontend.
       */
      feature_flags?: {
        [key: string]: boolean;
      } | null;
    };
    /**
     * BootstrapRevisions
     * @description Revisionsstände für Cache-Invalidierung und Diagnose.
     */
    BootstrapRevisions: {
      /**
       * Configuration
       * @default 0
       */
      configuration: number;
      /**
       * Model Registry
       * @default 0
       */
      model_registry: number;
      /**
       * Tool Registry
       * @default 0
       */
      tool_registry: number;
    };
    /**
     * BootstrapUser
     * @description Minimale, frontendfähige Darstellung des aktuellen Benutzers.
     *
     *     Es werden keine Session-Tokens, Passwortdaten oder internen
     *     Authentifizierungsinformationen ausgegeben.
     */
    BootstrapUser: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Roles */
      roles?: string[];
      /** Permissions */
      permissions?: string[];
      /**
       * Authenticated
       * @default false
       */
      authenticated: boolean;
    };
    /**
     * BootstrapVersions
     * @description Versionen der stabilen Backend- und Frontend-Verträge.
     */
    BootstrapVersions: {
      /**
       * Bootstrap Schema
       * @default 1.1
       */
      bootstrap_schema: string;
      /**
       * Ui Schema
       * @default 1.0
       */
      ui_schema: string;
      /**
       * Hierarchy Schema
       * @default 1.0
       */
      hierarchy_schema: string;
      /**
       * Chat Schema
       * @default 1.0
       */
      chat_schema: string;
      /**
       * Model Schema
       * @default 1.0
       */
      model_schema: string;
      /**
       * Tool Schema
       * @default 1.0
       */
      tool_schema: string;
      /**
       * Api
       * @default v1
       */
      api: string;
    };
    /** BulkConfigUpdateRequest */
    BulkConfigUpdateRequest: {
      /**
       * Values
       * @description Gruppierte Konfigurationswerte als Objekt { group: { key: value } }
       */
      values?: {
        [key: string]: {
          [key: string]: components['schemas']['JsonValue'];
        };
      };
      /**
       * Changes
       * @description Alternative sequentielle Änderungsbeschreibung [{group,key,value}, ...]
       */
      changes?: components['schemas']['ConfigChangeItem'][];
      /**
       * Expected Revision
       * @description Erwartete Revision zur Vermeidung von Race-Conditions.
       */
      expected_revision?: number | null;
    };
    /** CalendarCreate */
    CalendarCreate: {
      /** Name */
      name: string;
      /** Color */
      color?: string | null;
      /** Description */
      description?: string | null;
    };
    /** CalendarOut */
    CalendarOut: {
      /** Name */
      name: string;
      /** Color */
      color?: string | null;
      /** Description */
      description?: string | null;
      /** Id */
      id: string;
      /** Owner Id */
      owner_id?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** CalendarSelectionIn */
    CalendarSelectionIn: {
      /**
       * Selected
       * Format: date-time
       */
      selected: string;
      /** Note */
      note?: string | null;
    };
    /** CalendarSelectionOut */
    CalendarSelectionOut: {
      /** Id */
      id: string;
      /**
       * Selected
       * Format: date-time
       */
      selected: string;
      /** Note */
      note?: string | null;
      /** User Id */
      user_id?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** CalendarUpdate */
    CalendarUpdate: {
      /** Name */
      name?: string | null;
      /** Color */
      color?: string | null;
      /** Description */
      description?: string | null;
    };
    /**
     * ChatRequest
     * @description Öffentlicher, versionierter Chat-Request.
     *
     *     Zusätzliche Felder werden bewusst abgelehnt. Neue öffentliche Felder
     *     müssen explizit und versioniert ergänzt werden.
     */
    ChatRequest: {
      /**
       * Schema Version
       * @description Version des öffentlichen Chat-Request-Schemas.
       * @default 1.0
       * @constant
       */
      schema_version: '1.0';
      /**
       * Message
       * @description Nachricht des Benutzers.
       */
      message: string;
      /**
       * Conversation Id
       * @description Bestehende Unterhaltung, falls vorhanden.
       */
      conversation_id?: string | null;
      /**
       * Hierarchy Node Id
       * @description Aktiver generischer Hierarchieknoten.
       */
      hierarchy_node_id?: string | null;
      /**
       * Model Id
       * @description Optional angefordertes Modell.
       */
      model_id?: string | null;
      /**
       * Tool Ids
       * @description Optional angeforderte Tool-IDs.
       */
      tool_ids?: string[];
      /**
       * Metadata
       * @description Nicht sicherheitskritische Client-Metadaten.
       */
      metadata?: {
        [key: string]: components['schemas']['JsonValue'];
      };
    };
    /** ConfigChangeItem */
    ConfigChangeItem: {
      /** Group */
      group: string;
      /** Key */
      key: string;
      value: components['schemas']['JsonValue'];
    };
    /** ConfigDynamicOptionsResponse */
    ConfigDynamicOptionsResponse: {
      /** Source */
      source: string;
      /** Endpoint */
      endpoint?: string | null;
      /**
       * Value Field
       * @default id
       */
      value_field: string;
      /**
       * Label Field
       * @default name
       */
      label_field: string;
      /**
       * Description Field
       * @default description
       */
      description_field: string | null;
      /** Filters */
      filters?: {
        [key: string]: components['schemas']['JsonValue'];
      };
      /** Depends On */
      depends_on?: string | null;
      /** Dependency Parameter */
      dependency_parameter?: string | null;
    };
    /** ConfigEntryResponse */
    ConfigEntryResponse: {
      /** Group */
      group: string;
      /** Key */
      key: string;
      /** Full Key */
      full_key: string;
      /** Display Name */
      display_name: string;
      /** Description */
      description: string;
      value: components['schemas']['JsonValue'];
      default_value: components['schemas']['JsonValue'];
      /** Schema Version */
      schema_version: string;
      /** Value Type */
      value_type?: string | null;
      /** Value Schema */
      value_schema?: {
        [key: string]: components['schemas']['JsonValue'];
      };
      /** Editable */
      editable: boolean;
      /** Sensitive */
      sensitive: boolean;
      /**
       * Secret Configured
       * @default false
       */
      secret_configured: boolean;
      /** Requires Restart */
      requires_restart: boolean;
      /** Runtime Editable */
      runtime_editable: boolean;
      /** Nullable */
      nullable: boolean;
      /** Visibility */
      visibility: string;
      /** Allowed Scopes */
      allowed_scopes?: string[];
      /** Current Scope */
      current_scope: string;
      permissions?: components['schemas']['ConfigPermissionsResponse'] | null;
      ui: components['schemas']['ConfigUIResponse'];
      /**
       * Deprecated
       * @default false
       */
      deprecated: boolean;
      /** Deprecation Message */
      deprecation_message?: string | null;
      /** Replaced By */
      replaced_by?: string | null;
    };
    /** ConfigGroupResponse */
    ConfigGroupResponse: {
      /** Id */
      id: string;
      /** Label */
      label: string;
      /** Description */
      description?: string | null;
      /**
       * Order
       * @default 0
       */
      order: number;
      /** Entries */
      entries?: components['schemas']['ConfigEntryResponse'][];
    };
    /** ConfigListResponse */
    ConfigListResponse: {
      /**
       * Schema Version
       * @default 2.0
       * @constant
       */
      schema_version: '2.0';
      /** Revision */
      revision: number;
      /** Groups */
      groups?: components['schemas']['ConfigGroupResponse'][];
      /** Request Id */
      request_id?: string | null;
    };
    /** ConfigOptionResponse */
    ConfigOptionResponse: {
      /** Value */
      value: string | number | boolean;
      /** Label */
      label: string;
      /** Description */
      description?: string | null;
      /**
       * Disabled
       * @default false
       */
      disabled: boolean;
    };
    /** ConfigPermissionsResponse */
    ConfigPermissionsResponse: {
      /** Read */
      read: string;
      /** Write */
      write: string;
      /** Reveal Secret */
      reveal_secret?: string | null;
    };
    /** ConfigUIResponse */
    ConfigUIResponse: {
      /** Component */
      component?: string | null;
      /** Category */
      category?: string | null;
      /** Section */
      section?: string | null;
      /**
       * Order
       * @default 0
       */
      order: number;
      /** Placeholder */
      placeholder?: string | null;
      /** Help Text */
      help_text?: string | null;
      /** Unit */
      unit?: string | null;
      /**
       * Advanced
       * @default false
       */
      advanced: boolean;
      /**
       * Hidden
       * @default false
       */
      hidden: boolean;
      /**
       * Readonly
       * @default false
       */
      readonly: boolean;
      /** Options */
      options?: components['schemas']['ConfigOptionResponse'][];
      dynamic_options?: components['schemas']['ConfigDynamicOptionsResponse'] | null;
    };
    /**
     * ConfigUpdateRequest
     * @description Änderung eines einzelnen Konfigurationswertes.
     *
     *     `expected_revision` schützt vor dem unbeabsichtigten Überschreiben
     *     einer zwischenzeitlich geänderten Konfiguration.
     */
    ConfigUpdateRequest: {
      value: components['schemas']['JsonValue'];
      /**
       * Expected Revision
       * @description Vom Client zuletzt gelesene Konfigurationsrevision. Bei Abweichung wird die Änderung abgelehnt.
       */
      expected_revision?: number | null;
      /**
       * Reason
       * @description Optionale Begründung für das Audit-Log.
       */
      reason?: string | null;
    };
    /** ConfigUpdateResponse */
    ConfigUpdateResponse: {
      /**
       * Status
       * @default updated
       * @constant
       */
      status: 'updated';
      /** Group */
      group: string;
      /** Key */
      key: string;
      /** Revision */
      revision: number;
      /** Request Id */
      request_id?: string | null;
    };
    /** DocumentationIndexResponse */
    DocumentationIndexResponse: {
      /**
       * Schema Version
       * @default 1.0
       * @constant
       */
      schema_version: '1.0';
      /** Default Page Id */
      default_page_id?: string | null;
      /** Sections */
      sections?: components['schemas']['DocumentationSection'][];
    };
    /** DocumentationPageResponse */
    DocumentationPageResponse: {
      /**
       * Schema Version
       * @default 1.0
       * @constant
       */
      schema_version: '1.0';
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Section Id */
      section_id: string;
      /** Section Title */
      section_title: string;
      /** Content */
      content: string;
    };
    /** DocumentationPageSummary */
    DocumentationPageSummary: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /**
       * Description
       * @default
       */
      description: string;
    };
    /** DocumentationSection */
    DocumentationSection: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Pages */
      pages?: components['schemas']['DocumentationPageSummary'][];
    };
    /** EventCreate */
    EventCreate: {
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /**
       * Start
       * Format: date-time
       */
      start: string;
      /**
       * End
       * Format: date-time
       */
      end: string;
      /**
       * All Day
       * @default false
       */
      all_day: boolean | null;
    };
    /** EventOut */
    EventOut: {
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /**
       * Start
       * Format: date-time
       */
      start: string;
      /**
       * End
       * Format: date-time
       */
      end: string;
      /**
       * All Day
       * @default false
       */
      all_day: boolean | null;
      /** Id */
      id: string;
      /** Calendar Id */
      calendar_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** EventUpdate */
    EventUpdate: {
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      /** Start */
      start?: string | null;
      /** End */
      end?: string | null;
      /** All Day */
      all_day?: boolean | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Schema Version
       * @default 1.0
       */
      schema_version: string;
      /**
       * Api Version
       * @default v1
       */
      api_version: string;
      /**
       * Status
       * @default ok
       * @constant
       */
      status: 'ok';
      /** Environment */
      environment: string;
      /** Config Revision */
      config_revision: number;
      /** Security Profile */
      security_profile: {
        [key: string]: components['schemas']['JsonValue'];
      };
      /** Services */
      services: {
        [key: string]: components['schemas']['ServiceStatus'];
      };
      /** Request Id */
      request_id?: string | null;
    };
    /** HierarchyNode */
    HierarchyNode: {
      /** Id */
      id: string;
      /** Type */
      type: string;
      /** Name */
      name: string;
      /** Parent Id */
      parent_id?: string | null;
      /** System Prompt */
      system_prompt?: string | null;
      /** Tool Policy */
      tool_policy?: {
        [key: string]: boolean;
      };
      /** Config Overrides */
      config_overrides?: {
        [key: string]: components['schemas']['JsonValue'];
      };
      /** Metadata */
      metadata?: {
        [key: string]: components['schemas']['JsonValue'];
      };
      /** Effective Prompt */
      effective_prompt?: string | null;
      /** Effective Tools */
      effective_tools?: {
        [key: string]: boolean;
      };
      /** Effective Config */
      effective_config?: {
        [key: string]: components['schemas']['JsonValue'];
      };
      /** Available Actions */
      available_actions?: string[];
      /** Children */
      children?: components['schemas']['HierarchyNode'][];
    };
    /** HierarchyNodeCreate */
    HierarchyNodeCreate: {
      /** Type */
      type: string;
      /** Name */
      name: string;
      /** Parent Id */
      parent_id?: string | null;
      /** System Prompt */
      system_prompt?: string | null;
      /** Tool Policy */
      tool_policy?: {
        [key: string]: boolean;
      };
      /** Config Overrides */
      config_overrides?: {
        [key: string]: components['schemas']['JsonValue'];
      };
      /** Metadata */
      metadata?: {
        [key: string]: components['schemas']['JsonValue'];
      };
    };
    /** HierarchyNodeUpdate */
    HierarchyNodeUpdate: {
      /** Name */
      name?: string | null;
      /** System Prompt */
      system_prompt?: string | null;
      /** Tool Policy */
      tool_policy?: {
        [key: string]: boolean;
      } | null;
      /** Config Overrides */
      config_overrides?: {
        [key: string]: components['schemas']['JsonValue'];
      } | null;
      /** Metadata */
      metadata?: {
        [key: string]: components['schemas']['JsonValue'];
      } | null;
    };
    /**
     * HierarchyTreeResponse
     * @description API-Vertrag für die Hierarchie – kompatibel mit Frontend-HierarchyTree.
     */
    HierarchyTreeResponse: {
      /**
       * Schema Version
       * @default 1.0
       */
      schema_version: string;
      /** Root */
      root: {
        [key: string]: components['schemas']['JsonValue'];
      };
      /**
       * Revision
       * @description Optionale globale Revision für Cache-Invalidierung.
       */
      revision?: number | null;
    };
    JsonValue: unknown;
    /**
     * ModelCapability
     * @description Bekannte technische Fähigkeiten eines Modells.
     *
     *     Unbekannte Fähigkeiten können zusätzlich über `additional`
     *     übertragen werden, ohne den stabilen Vertrag zu brechen.
     */
    ModelCapability: {
      /**
       * Chat
       * @default false
       */
      chat: boolean;
      /**
       * Streaming
       * @default false
       */
      streaming: boolean;
      /**
       * Tool Calling
       * @default false
       */
      tool_calling: boolean;
      /**
       * Vision
       * @default false
       */
      vision: boolean;
      /**
       * Embeddings
       * @default false
       */
      embeddings: boolean;
      /**
       * Structured Output
       * @default false
       */
      structured_output: boolean;
      /** Additional */
      additional?: string[];
    };
    /**
     * ModelEntry
     * @description Öffentlicher, frontendfähiger Modelleintrag.
     *
     *     Interne Dateipfade, Zugangsdaten und Provider-Secrets werden nicht
     *     an das Frontend weitergegeben.
     */
    ModelEntry: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Provider */
      provider: string;
      /** Backend */
      backend?: string | null;
      /** Description */
      description?: string | null;
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /**
       * Available
       * @default true
       */
      available: boolean;
      /**
       * Selectable
       * @default true
       */
      selectable: boolean;
      /**
       * Default
       * @default false
       */
      default: boolean;
      capabilities?: components['schemas']['ModelCapability'];
      limits?: components['schemas']['ModelLimits'];
      /** Tags */
      tags?: string[];
      /** Metadata */
      metadata?: {
        [key: string]: components['schemas']['JsonValue'];
      };
    };
    /** ModelLimits */
    ModelLimits: {
      /** Context Window */
      context_window?: number | null;
      /** Max Output Tokens */
      max_output_tokens?: number | null;
    };
    /** ModelListResponse */
    ModelListResponse: {
      /**
       * Schema Version
       * @default 1.0
       */
      schema_version: string;
      /**
       * Registry Revision
       * @default 0
       */
      registry_revision: number;
      /**
       * Config Revision
       * @default 0
       */
      config_revision: number;
      /** Items */
      items: components['schemas']['ModelEntry'][];
      /** Request Id */
      request_id?: string | null;
    };
    /** ProviderEntry */
    ProviderEntry: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * Model Count
       * @default 0
       */
      model_count: number;
      /**
       * Available Model Count
       * @default 0
       */
      available_model_count: number;
    };
    /** ProviderListResponse */
    ProviderListResponse: {
      /**
       * Schema Version
       * @default 1.0
       */
      schema_version: string;
      /**
       * Registry Revision
       * @default 0
       */
      registry_revision: number;
      /** Items */
      items?: components['schemas']['ProviderEntry'][];
      /** Request Id */
      request_id?: string | null;
    };
    /** ServiceStatus */
    ServiceStatus: {
      /**
       * Status
       * @enum {string}
       */
      status: 'up' | 'down' | 'unknown';
    };
    /**
     * SettingsAvailability
     * @enum {string}
     */
    SettingsAvailability: 'available' | 'prepared' | 'planned';
    /** SettingsCatalogResponse */
    SettingsCatalogResponse: {
      /**
       * Schema Version
       * @default 1.0
       * @constant
       */
      schema_version: '1.0';
      /** Groups */
      groups: components['schemas']['SettingsGroupDescriptor'][];
      /** Request Id */
      request_id?: string | null;
    };
    /**
     * SettingsControl
     * @enum {string}
     */
    SettingsControl:
      'text' | 'textarea' | 'number' | 'boolean' | 'select' | 'multiselect' | 'readonly' | 'link';
    /** SettingsFieldDescriptor */
    SettingsFieldDescriptor: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      source: components['schemas']['SettingsSource'];
      /** @default prepared */
      availability: components['schemas']['SettingsAvailability'];
      /** @default readonly */
      control: components['schemas']['SettingsControl'];
      /** Config Group */
      config_group?: string | null;
      /** Config Key */
      config_key?: string | null;
      /** Endpoint */
      endpoint?: string | null;
      /**
       * Editable
       * @default false
       */
      editable: boolean;
      /**
       * Sensitive
       * @default false
       */
      sensitive: boolean;
      /**
       * Requires Confirmation
       * @default false
       */
      requires_confirmation: boolean;
      /**
       * Restart Required
       * @default false
       */
      restart_required: boolean;
      /**
       * Options
       * @default []
       */
      options: components['schemas']['SettingsOption'][];
      /** Minimum */
      minimum?: number | null;
      /** Maximum */
      maximum?: number | null;
      /**
       * Order
       * @default 0
       */
      order: number;
      /**
       * Tags
       * @default []
       */
      tags: string[];
    };
    /** SettingsGroupDescriptor */
    SettingsGroupDescriptor: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Icon */
      icon: string;
      /** Order */
      order: number;
      /** @default prepared */
      availability: components['schemas']['SettingsAvailability'];
      /**
       * Sections
       * @default []
       */
      sections: components['schemas']['SettingsSectionDescriptor'][];
    };
    /** SettingsOption */
    SettingsOption: {
      /** Value */
      value: string;
      /** Label */
      label: string;
    };
    /** SettingsSectionDescriptor */
    SettingsSectionDescriptor: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /**
       * Order
       * @default 0
       */
      order: number;
      /** @default prepared */
      availability: components['schemas']['SettingsAvailability'];
      /**
       * Fields
       * @default []
       */
      fields: components['schemas']['SettingsFieldDescriptor'][];
    };
    /**
     * SettingsSource
     * @enum {string}
     */
    SettingsSource: 'config' | 'resource' | 'runtime' | 'local_preference';
    /**
     * ToolCapabilities
     * @description Technische Fähigkeiten eines Tools.
     *
     *     Diese Angaben beschreiben lediglich die Tool-Schnittstelle.
     *     Sie stellen keine Ausführungsberechtigung dar.
     */
    ToolCapabilities: {
      /**
       * Streaming
       * @default false
       */
      streaming: boolean;
      /**
       * Confirmation Required
       * @default false
       */
      confirmation_required: boolean;
      /**
       * Idempotent
       * @default false
       */
      idempotent: boolean;
      /**
       * Read Only
       * @default false
       */
      read_only: boolean;
      /**
       * Supports Cancellation
       * @default false
       */
      supports_cancellation: boolean;
      /** Additional */
      additional?: string[];
    };
    /**
     * ToolEntry
     * @description Öffentlicher, frontendfähiger Tool-Eintrag.
     *
     *     Interne Python-Pfade, Importnamen, Zugangsdaten und ausführbare
     *     Implementierungsdetails werden nicht ausgegeben.
     */
    ToolEntry: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Version
       * @default 1.0.0
       */
      version: string;
      /** Description */
      description?: string | null;
      /** Category */
      category?: string | null;
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /**
       * Available
       * @default true
       */
      available: boolean;
      /**
       * Selectable
       * @default true
       */
      selectable: boolean;
      capabilities?: components['schemas']['ToolCapabilities'];
      input_schema?: components['schemas']['ToolInputSchema'];
      /** Output Schema */
      output_schema?: {
        [key: string]: components['schemas']['JsonValue'];
      } | null;
      /** Required Permissions */
      required_permissions?: string[];
      /** Tags */
      tags?: string[];
      /** Metadata */
      metadata?: {
        [key: string]: components['schemas']['JsonValue'];
      };
    };
    /**
     * ToolInputSchema
     * @description Öffentliche Beschreibung des Tool-Eingabeschemas.
     *
     *     Das Schema bleibt JSON-Schema-artig, damit das Frontend daraus
     *     generische Formulare erzeugen kann.
     */
    ToolInputSchema: {
      /**
       * Type
       * @default object
       */
      type: string;
      /** Properties */
      properties?: {
        [key: string]: components['schemas']['JsonValue'];
      };
      /** Required */
      required?: string[];
      /** Additionalproperties */
      additionalProperties?:
        | boolean
        | {
            [key: string]: components['schemas']['JsonValue'];
          }
        | null;
    } & {
      [key: string]: unknown;
    };
    /** ToolListResponse */
    ToolListResponse: {
      /**
       * Schema Version
       * @default 1.0
       */
      schema_version: string;
      /**
       * Registry Revision
       * @default 0
       */
      registry_revision: number;
      /**
       * Config Revision
       * @default 0
       */
      config_revision: number;
      /** Items */
      items: components['schemas']['ToolEntry'][];
      /** Request Id */
      request_id?: string | null;
    };
    /** UISchemaDocument */
    UISchemaDocument: {
      /**
       * Schema Name
       * @default default
       */
      schema_name: string;
      /**
       * Schema Version
       * @default 1.0
       */
      schema_version: string;
      /** Node Types */
      node_types?: {
        [key: string]: components['schemas']['JsonValue'];
      };
      /** Forms */
      forms?: {
        [key: string]: components['schemas']['JsonValue'];
      };
      /** Components */
      components?: {
        [key: string]: components['schemas']['JsonValue'];
      };
      /** Actions */
      actions?: {
        [key: string]: components['schemas']['JsonValue'];
      };
      /** Metadata */
      metadata?: {
        [key: string]: components['schemas']['JsonValue'];
      };
    } & {
      [key: string]: unknown;
    };
    /**
     * UISchemaResponse
     * @description Transportvertrag des API-Endpunkts.
     *
     *     `ui_schema` wird im öffentlichen JSON-Vertrag weiterhin als
     *     `schema` serialisiert.
     */
    UISchemaResponse: {
      /**
       * Api Schema Version
       * @default 1.0
       */
      api_schema_version: string;
      /** Ui Schema Version */
      ui_schema_version: string;
      /**
       * Config Revision
       * @default 0
       */
      config_revision: number;
      schema: components['schemas']['UISchemaDocument'];
      /** Request Id */
      request_id?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** _MovePayload */
    _MovePayload: {
      /**
       * New Parent Id
       * @description Neuer Elternknoten oder null für Root
       */
      new_parent_id?: string | null;
    };
    /** _ReorderItem */
    _ReorderItem: {
      /** Id */
      id: string;
      /** New Parent Id */
      new_parent_id?: string | null;
      /** New Position */
      new_position: number;
    };
    /** _ReorderPayload */
    _ReorderPayload: {
      /** Items */
      items: components['schemas']['_ReorderItem'][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  get_settings_catalog_api_v1_settings_catalog_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingsCatalogResponse'];
        };
      };
    };
  };
  bootstrap_api_v1_bootstrap_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BootstrapResponse'];
        };
      };
    };
  };
  ui_schema_api_v1_ui_schema_get: {
    parameters: {
      query?: {
        /** @description Deaktivierte Schemaelemente mit ausgeben. Für administrative Ansichten vorgesehen. */
        include_disabled?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Das UI-Schema wurde erfolgreich erzeugt. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UISchemaResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Das erzeugte UI-Schema ist ungültig. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Der UI-Schema-Builder ist nicht verfügbar. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  select_date_api_v1_calendar_selection_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CalendarSelectionIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CalendarSelectionOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_calendars_api_v1_calendars__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CalendarOut'][];
        };
      };
    };
  };
  create_calendar_api_v1_calendars__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CalendarCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CalendarOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_calendar_api_v1_calendars__calendar_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        calendar_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CalendarOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_calendar_api_v1_calendars__calendar_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        calendar_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  patch_calendar_api_v1_calendars__calendar_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        calendar_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CalendarUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CalendarOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_events_api_v1_calendars__calendar_id__events_get: {
    parameters: {
      query?: {
        time_min?: string | null;
        time_max?: string | null;
      };
      header?: never;
      path: {
        calendar_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_event_api_v1_calendars__calendar_id__events_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        calendar_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EventCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_event_api_v1_calendars__calendar_id__events__event_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        calendar_id: string;
        event_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_event_api_v1_calendars__calendar_id__events__event_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        calendar_id: string;
        event_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  patch_event_api_v1_calendars__calendar_id__events__event_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        calendar_id: string;
        event_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EventUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  hierarchy_api_v1_hierarchy_get: {
    parameters: {
      query?: {
        /** @description Optionaler Startknoten. */
        root_id?: string | null;
        /** @description Optionale maximale Rekursionstiefe. */
        max_depth?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HierarchyTreeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_hierarchy_node_api_v1_hierarchy_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['HierarchyNodeCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HierarchyNode'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_hierarchy_node_api_v1_hierarchy__node_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        node_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_hierarchy_node_api_v1_hierarchy__node_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        node_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['HierarchyNodeUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HierarchyNode'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  move_hierarchy_node_api_v1_hierarchy__node_id__move_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        node_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['_MovePayload'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HierarchyNode'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reorder_hierarchy_nodes_api_v1_hierarchy_reorder_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['_ReorderPayload'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_documentation_api_v1_documentation_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentationIndexResponse'];
        };
      };
    };
  };
  get_documentation_page_api_v1_documentation_pages__page_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        page_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentationPageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  providers_api_v1_models_providers_get: {
    parameters: {
      query?: {
        include_disabled?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProviderListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  models_api_v1_models_get: {
    parameters: {
      query?: {
        /** @description Deaktivierte Modelle mit ausgeben. Für Admin-Oberflächen vorgesehen. */
        include_disabled?: boolean;
        /** @description Optional nach einer Fähigkeit filtern. */
        capability?:
          | ('chat' | 'streaming' | 'tool_calling' | 'vision' | 'embeddings' | 'structured_output')
          | null;
        /** @description Optional nach Provider filtern. */
        provider?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Modellliste wurde geladen. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ModelListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Die Modellregistrierung ist nicht verfügbar. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  tools_api_v1_tools_get: {
    parameters: {
      query?: {
        /** @description Deaktivierte Tools mit ausgeben. Für administrative Oberflächen vorgesehen. */
        include_disabled?: boolean;
        /** @description Aktuell nicht verfügbare Tools mit ausgeben. */
        include_unavailable?: boolean;
        /** @description Optional nach Tool-Kategorie filtern. */
        category?: string | null;
        /** @description Optional nach einer Fähigkeit filtern. */
        capability?:
          | (
              | 'streaming'
              | 'confirmation_required'
              | 'idempotent'
              | 'read_only'
              | 'supports_cancellation'
            )
          | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tool-Liste wurde geladen. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ToolListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Die Tool-Registry ist nicht verfügbar. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  stream_chat_api_v1_chat_stream_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatRequest'];
      };
    };
    responses: {
      /** @description SSE-Datenstrom wurde gestartet. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
          'text/event-stream': string;
        };
      };
      /** @description Der Benutzer ist nicht berechtigt. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Die Chat-Anfrage ist ungültig. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Der ChatService ist nicht verfügbar. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_config_api_v1_config_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConfigListResponse'];
        };
      };
    };
  };
  bulk_update_config_api_v1_config_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BulkConfigUpdateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_config_api_v1_config__group___key__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        group: string;
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfigUpdateRequest'];
      };
    };
    responses: {
      /** @description Konfiguration wurde aktualisiert. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConfigUpdateResponse'];
        };
      };
      /** @description Keine Berechtigung für die Änderung. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Die Konfiguration wurde zwischenzeitlich geändert. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Gruppe, Schlüssel oder Wert ist ungültig. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
}
